# Docker-compose version
version: '3.9'

services:
  proxy:
    build: ./app/proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./app/proxy/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./app/proxy/tls.yml:/etc/traefik/tls.yml:ro"
      - "./app/proxy/certs/:/etc/certs/:ro"

  jupyterhub:
    build: ./app/jupyterhub
    container_name: jupyterhub
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:rw"
    - "jupyterhub-data:/data:rw"
    - "./app/jupyterhub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
    environment:
      - ACTIVE_SERVER_LIMIT=${ACTIVE_SERVER_LIMIT}
      - ACTIVITY_RESOLUTION=${ACTIVITY_RESOLUTION}
      - MEM_LIMIT=${MEM_LIMIT}
      - CPU_LIMIT=${CPU_LIMIT}
      - APPDATA_DIR=${APPDATA_DIR}
      - DOCKER_NOTEBOOK_IMAGE=notebook_img
      - DOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
      - HOST=${HOST}
      - JUPYTERHUB_IDLE_CULLER_TIMEOUT=${IDLE_CULLER_TIMEOUT}
    labels:
      - "traefik.http.routers.jupyterhub.rule=Host(`${HOST}`)"
      - "traefik.http.routers.jupyterhub.tls=true"

  notebook:
    build: ./app/notebook
    image: notebook_img
    container_name: notebook-throwaway
    network_mode: none
    command: echo

volumes:
  jupyterhub-data: